# Generated by Django 3.1.2 on 2020-11-01 06:43

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20201031_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(upload_to=post.models.user_directory_path, verbose_name='Picture'),
        ),
    ]
