# Generated by Django 3.1.2 on 2020-10-24 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ig', '0002_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
