# Generated by Django 3.1.2 on 2020-10-31 16:06

import cloudinary.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ig', '0003_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='picture'),
            preserve_default=False,
        ),
    ]
