# Generated by Django 3.1.2 on 2020-11-01 06:43

from django.db import migrations, models
import ig.models


class Migration(migrations.Migration):

    dependencies = [
        ('ig', '0004_auto_20201031_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=ig.models.user_directory_path, verbose_name='Picture'),
        ),
    ]
